name: Run Pytest on Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub 리포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Python 설정 (필요시 버전 변경 가능)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-dev.txt

      # 4. Pytest 실행
      - name: Run tests with pytest
        run: |
          pytest tests/
